services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9100:9100"
    command: tail -f /dev/null
    volumes:
      - .:/root/project
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
