services:
  <my_project_name>:
    container_name: <my_project_name>
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile.dev
    ports:
      - "4051:4051"
    command: tail -f /dev/null
    volumes:
      - ..:/<my_project_name>
    env_file:
      - ../.env
    depends_on:
      characters_db:
        condition: service_healthy

volumes:
  characters_db: