services:
  main:
    container_name: main
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile.dev
    ports:
      - "4050:4050"
    command: tail -f /dev/null
    volumes:
      - ..:/root/project
    env_file:
      - ../.env
    deploy:
      resources:
        limits:
          memory: 4G
