services:
  <my_project_name>:
    container_name: <my_project_name>
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile.dev
    command: tail -f /dev/null
    volumes:
      - ..:/<my_project_name>
    env_file:
      - ../.env
